# Generated by Django 5.2.10 on 2026-01-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('reading_minute', models.PositiveIntegerField(default=0)),
                ('content_markdown', models.TextField()),
                ('content_html', models.TextField()),
                ('tg_link', models.URLField()),
                ('is_published', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
